name: Test the library

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: NPM install, lint, build, and test
        run: |
          npm ci
          npm run lint
          npm run build -- --prod
          npm run test -- --project=@ngneat/input-mask --watch=false --browsers=ChromeHeadless
          npm run build:lib

      - name: Trigger release
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release --debug
