name: Publish the library

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: NPM install, build, and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run build -- --prod
          npm run build:lib
          npx semantic-release --debug
