name: Test the library

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: NPM install, lint, build, and test
        run: |
          npm ci
          npm run lint
          npm run build -- --prod
          npm run test -- --watch=false --browsers=ChromeHeadless
          npm run build:lib

      - name: Trigger release workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
